// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNL9o9qyKmKHvfo_GhW6-siSRwP5R24Ds',
    appId: '1:501606116930:web:0e57209a200adc6c4087db',
    messagingSenderId: '501606116930',
    projectId: 'chat-app-8b5af',
    authDomain: 'chat-app-8b5af.firebaseapp.com',
    storageBucket: 'chat-app-8b5af.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvOgVahmFkzQFNXlFiJ49BgymHI6BxwxQ',
    appId: '1:501606116930:android:3edc45455762f1074087db',
    messagingSenderId: '501606116930',
    projectId: 'chat-app-8b5af',
    storageBucket: 'chat-app-8b5af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDJvl0jxp5KlQDnjC77iWWf6aSAtWPwdI',
    appId: '1:501606116930:ios:269172963c5f4e364087db',
    messagingSenderId: '501606116930',
    projectId: 'chat-app-8b5af',
    storageBucket: 'chat-app-8b5af.appspot.com',
    iosClientId: '501606116930-e17g22qfm6rdkvg50cs4da9c2i7b7lgl.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDJvl0jxp5KlQDnjC77iWWf6aSAtWPwdI',
    appId: '1:501606116930:ios:269172963c5f4e364087db',
    messagingSenderId: '501606116930',
    projectId: 'chat-app-8b5af',
    storageBucket: 'chat-app-8b5af.appspot.com',
    iosClientId: '501606116930-e17g22qfm6rdkvg50cs4da9c2i7b7lgl.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
